# Unordered list style
MD004:
  style: dash

# Line length
MD013:
  code_block_line_length: 80
  code_blocks: true
  heading_line_length: 80
  headings: true
  line_length: 80
  stern: false
  strict: false
  tables: false

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced
